### ISSUE TITLE
Checklist could be different than 2 entries

### ISSUE THREAD

**Issue by radio24** [nyxnor/onionservice#3]
https://github.com/nyxnor/onionservice/blob/d429606e546b65321ce8b7191cd23702f8871dbb/onionservice-tui#L70

**Issue**
It seems (I use whiptail instead of dialog) that the "2" representing two entries is hardcoded in this line of code. However, someone may have only one or several entries. 

**Describe the solution you'd like**
For the above reasons, I propose to replace "2" with "$i". To be sure that the list is not getting too long and is fitting to a little LCD display, the entire code could look like that:

```
if [ $i -gt 11 ]; then i=11; fi
CHOICE_SERVICE="$(dialog --clear --backtitle "${BACKTITLE}" --title "${TITLE}" --"${DIALOG_TYPE}" "${MENU}" \
"$((i+8))" 80 ${i} ${SERVICE_LIST} 2>&1 >/dev/tty)"
```

**Additional remarks**
I didn't submit a pull request yet because I don't use dialog, and I'm not entirely sure it reacts like whiptail.

**Comment by nyxnor** [comment]
### On dialog, one or more services works fine 

#### 1 service:
![image](https://user-images.githubusercontent.com/69700936/140632461-bf4ec562-2b77-400b-a973-67aa17fb7cf2.png)


#### 3 services:
![image](https://user-images.githubusercontent.com/69700936/140632474-0322a9eb-b0ad-4e16-a928-37857fccecb1.png)


### LCD display

Yes, max will be pinned, so this change would be accepted, if possible to consider also the AUTH_* and any other relevant option to pin/fix lines regarding clients names (why 11?).
```sh
    [ "${i}" -gt 11 ] && i=11
    # shellcheck disable=SC2086
    CHOICE_SERVICE="$(dialog --clear --backtitle "${BACKTITLE}" --title "${TITLE}" --"${DIALOG_TYPE}" "${MENU}" \
    "$((i+8))" 80 ${i} ${SERVICE_LIST} 2>&1 >/dev/tty)"
```

![image](https://user-images.githubusercontent.com/69700936/140632634-54d0e2da-0ea9-4bf6-a297-649a58b3af57.png)

**Comment by radio24** [comment]
11 because this is the maximum number I can squeeze into my [PiTFT Plus 480x320 3.5"](https://www.adafruit.com/product/2441).
